test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Google Cloud Storage — MVP/Desenvolvimento
# Substitua os valores abaixo pelas suas credenciais reais
google:
  service: GCS
  project: <%= Rails.application.credentials.dig(:gcs, :project_id) %>
  credentials: <%= Rails.application.credentials.dig(:gcs, :keyfile_path) %>
  bucket: <%= Rails.application.credentials.dig(:gcs, :bucket) %>
